export enum NatureCulture {
    S = "S", P = "P", AB = "AB", T = "T",
    E = "E", J = "J",
    VI = "VI",
    L = "L",
    AG = "AG",
    BT = "BT",
    BS = "BS",
    BP = "BP",
    VE = "VE",
    PA = "PA",
    BR = "BR",
    B = "B",
    CH = "CH",
    BF = "BF",
    A = "CA",
    BM = "BM",
    PP = "PP",
    BO = "BO",
    PC = "PC",
    TP = "TP",
    LB = "LB",
    PH = "PH",
    PE = "PE"
}