export enum NatureCultureSpeciales {
    MARE = "MARE",
    POTAGER = "POTAG",
    SPORT = "SPORT",
    ACACI = "ACACI",
    JARDIN = "JARD",
    PATURAGE = "PATUR",
    FRICHE = "FRICH",
    CHEMIN = "CHEM",
    BIEF = "BIEF",
    FOSSE = "FOSSE",
    PARC = "PARC",
    ETANG = "ETANG",
    CANAL = "CANAL",
    LEGUMES = "LEGUM",
    PIN = "PIN",
    MARAIS = "MARAI",
    IMM = "IMM",
    FER = "FER",
    SAPIN = "SAPIN",
    VDQS = "VDQS",
    CHASS = "CHASS", RUE = "RUE", SERRE = "SERRE", PEPIN = "PEPIN", VAOC = "VAOC",
    CHENE = "CHENE",HETRE =  "HETRE", PACAG = "PACAG",FLORE =  "FLOR",BROUS =  "BROUS", VAGUE ="VAGUE",ABRID = "ABRIC",
    OLIVE = "OLIVE", CAMP = "CAMP", RESINES = "RESIN", CHAT = "CHAT", CHTRU = "CHTRU", MARNA = "MARNA",
    CITRON = "CITRO",ORANGES =  "ORANG",ROC =  "ROC",RAIS =  "RAIS",EPICES =  "EPICE",HORT =  "HORT", RUINE = "RUINE",
    LAC = "LAC",BOUL =  "BOUL", SABLE = "SABLE",BALLA =  "BALLA", CIDRE = "CIDRE",
    NOYER = "NOYER",
    SAULE = "SAULE",
    CERISES = "CERIS",
    EUCALYPTUS = "EUCAL",
    POIRE = "POIRE",
    AMANDES = "AMAND",
    MARCHERS = "MAREC",
    BASS = "BASS",
    CHVER = "CHVER",
    RIZ = "RIZ",
    BRUYERES = "BRUY",
    FOUGERES = "FOUG",
    VIVIE = "VIVIE",
    SART = "SART",
    CALIR = "CLAIR",
    SALIN = "SALIN", MOTTE = "MOTTE",
    DIGE = "DIGUE",CASS =  "CASS", JOUAL = "JOUAL",HAIES =  "HAIES",INTEN =  "INTEN",
    PECHES = "PECH", PATIS = "PATIS", CRESS = "CRESS", FAMIL = "FAMIL", RESER = "RESER", PASS = "PASS",
    ASPERGES = "ASPER", AUMN = "AULN",
    FRAMBOISES = "FRAMB", POMME = "POMME", MARAM = "MARAM", PRUNE = "PRUNE", NOISE = "NOISE",
    AEROD = "AEROD",TOURB =  "TOURB",
    PECHE = "PECHE",BTIGE =  "BTIGE", MAQUI = "MAQUI",CHLIE =  "CHLIE",
    CEDRA = "CEDRA",
    PIEDS = "PIEDS",
    CERCLE = "CERCL",
    GRAVE = "GRAVE",
    ALLEE = "ALLEE",
    AIRE = "AIRE",
    PAFEU = "PAFEU",
    LAGUNE = "LAGUN",
    RIVAGE = "RIVAG",
    HTIGE = "HTIGE",
    MARN = "MARN",
    PLVEN = "PLVEN",
    KIWIS = "KIWIS",
    VIGNE = "VIGNE",
    GAREN = "GAREN",
    JETT = "JETT",
    HERB = "HERB",
    ALLUV = "ALLUV",
    DUNE = "DUNE",
    NPECH = "NPECH",
    ARGIL = "ARGIL",
    TOUTA = "TOUYA",
    FONT = "FONT",
    ESPAL = "ESPAL",
    HUITRE = "HUITR",
    IMPRO = "IMPRO",
    PROTE = "PROTE",
    FILAO = "FILAO",
    CRYPT = "CRYPT"
}