export enum Section {
    AH = "AH",
    AE = "AE",
    B = "B",
    AM = "AM",
    D = "D",
    A = "A",
    AI = "AI",
    AK = "AK",
    ZA = "ZA",
    ZH = "ZH",
    ZC = "ZC",
    AP = "AP",
    ZD = "ZD",
    WA = "WA",
    C = "C",
    AL = "AL",
    AO = "AO",
    CL = "CL",
    AD = "AD",
    CP = "CP",
    CN = "CN",
    AB = "AB",ZI =  "ZI",ZM =  "ZM",CI =  "CI",BC =  "BC",ZL =  "ZL",ZE =  "ZE",AV =  "AV", E = "E", ZK = "ZK",F =  "F",
    WH = "WH", AT = "AT", ZS = "ZS", AC = "AC", AY = "AY", AZ = "AZ", BL = "BL", ZN = "ZN", YA = "YA",
    YH = "YH",ZR =  "ZR",BN =  "BN", H = "H", AA = "AA", AR = "AR",AS =  "AS",WE =  "WE",WR =  "WR",
    CD = "CD", ZB = "ZB", CH = "CH", BD = "BD", CS = "CS", BE = "BE", WB = "WB", WI = "WI", AX = "AX", AN = "AN",
    BH = "BH", BK = "BK",
    BM = "BM",CV =  "CV",CW =  "CW",AW =  "AW", WC = "WC",WO =  "WO",CK =  "CK", BI = "BI", ZP = "ZP",
    BB = "BB",ZT =  "ZT",
    BP = "BP",
    BO = "BO",
    ZW = "ZW",
    G = "G",
    I = "I",
    ZX = "ZX",
    BX = "BX",
    WP = "WP",
    X = "X",
    Z = "Z",
    CR = "CR",
    WV = "WV",
    WK = "WK",
    CO = "CO",
    WM = "WM",
    WL = "WL",
    BT = "BT",
    BZ = "BZ",
    BS = "BS",
    WD = "WD",
    CM = "CM",
    BW = "BW",
    BR = "BR",WT =  "WT",
    ZV = "ZV",
    YD = "YD",
    WS = "WS",
    YE = "YE",
    K = "K",
    R = "R",
    M = "M",
    VI = "VI",
    VK = "VK",
    VB = "VB",
    BA = "BA",
    O = "O",
    L = "L", J = "J",
    P = "P",
    BY = "BY",
    N = "N",
    ZY = "ZY",
    WW = "WW",
    VM = "VM",
    VP = "VP",
    WN = "WN",
    W = "W",
    Y = "Y",
    YB = "YB",
    YM = "YM",
    YL = "YL",
    CE = "CE",
    BV = "BV", DL = "DL", YO = "YO", DM = "DM", V = "V", CZ = "CZ", YC = "YC", CY = "CY", YI = "YI", YN = "YN",
    CX = "CX", CT = "CT", DE = "DE",
    DK = "DK", DH = "DH",XI =  "XI",XA =  "XA",
    XC = "XC",VA =  "VA", XD = "XD", YR = "YR",
    YP = "YP",YT =  "YT", YS = "YS",XW =  "XW", YX = "YX", YV = "YV",
    XK = "XK", XX = "XX", YK = "YK", YW = "YW", DA = "DA", DD = "DD", DI = "DI",
    XM = "XM", XY = "XY", XL = "XL", XP = "XP", YZ = "YZ", XB = "XB",
    XO = "XO",
    XT = "XT",
    YY = "YY",
    T = "T",
    ZZ = "ZZ",
    DN = "DN",
    DZ = "DZ",
    DO = "DO",
    EI = "EI",
    EL = "EL",
    S = "S",
    EK = "EK",
    EH = "EH",
    DS = "DS",
    U = "U",
    DY = "DY",
    Q = "Q",
    DX = "DX",
    LT = "LT",
    HS = "HS",
    HI = "HI",
    HC = "HC",
    HA = "HA",
    HB = "HB",
    LN = "LN",
    LA = "LA",
    LE = "LE",
    IS = "IS",
    KN = "KN", EC = "EC",HW =  "HW",LR =  "LR",LC =  "LC",
    LS = "LS", IW = "IW", LB = "LB", KV = "KV",KY =  "KY",IX =  "IX",IV =  "IV",
    IY = "IY",KS =  "KS",LV =  "LV",EB =  "EB",LD =  "LD", HK = "HK", HE = "HE",IR =  "IR",
    LK = "LK",EZ =  "EZ", KT = "KT",KM =  "KM",
    KR = "KR",
    IZ = "IZ",
    KO = "KO",
    KP = "KP",
    LI = "LI",
    HD = "HD",
    IM = "IM",
    ED = "ED",
    KI = "KI",
    IP = "IP",
    LH = "LH",
    IO = "IO",
    KZ = "KZ",
    HZ = "HZ",
    KL = "KL",
    EX = "EX",
    HN = "HN",
    LM = "LM",
    LP = "LP",KH =  "KH",
    HY = "HY",
    IN = "IN",
    ID = "ID",
    EP = "EP",
    EW = "EW",
    IE = "IE",
    EO = "EO",
    ES = "ES",
    ET = "ET",
    HO = "HO",
    KE = "KE",
    HR = "HR", HM = "HM", ER = "ER",HL =  "HL", HT = "HT",IC =  "IC", EY = "EY",HP =  "HP",
    EA = "EA", HX = "HX", IT = "IT",HV =  "HV", KC = "KC", IH = "IH", EV = "EV", LW = "LW", MS = "MS", MR = "MR",
    MH = "MH", NX = "NX", KW = "KW",
    LX = "LX",NS =  "NS",NB =  "NB",
    NK = "NK",MI =  "MI",NE =  "NE",MO =  "MO", NH = "NH",
    NC = "NC", MY = "MY", MP = "MP", KX = "KX", OL = "OL", NW = "NW", MC = "MC", NM = "NM", MK = "MK", OE = "OE",
    NP = "NP",ND =  "ND",NO =  "NO",
    MD = "MD",OI =  "OI",
    OC = "OC",
    NY = "NY",
    OD = "OD",
    NR = "NR",
    NT = "NT",
    ME = "ME",
    MN = "MN",
    MV = "MV",
    OH = "OH",
    LY = "LY",
    NZ = "NZ",
    LZ = "LZ",
    EM = "EM",
    NL = "NL",
    ML = "ML",
    NV = "NV",
    NI = "NI",
    OM = "OM",
    DR = "DR",
    MA = "MA",DB =  "DB",
    NA = "NA",
    CA = "CA",
    DW = "DW",
    DT = "DT",
    MX = "MX",
    MZ = "MZ",
    MT = "MT",
    ON = "ON",
    OB = "OB",
    EN = "EN",
    DC = "DC",
    DV = "DV",
    MW = "MW",
    CC = "CC",
    CB = "CB",
    DP = "DP",
    EE = "EE",
    ZF = "ZF",
    ZG = "ZG",
    XE = "XE", XR = "XR", XN = "XN", XH = "XH",
    PX = "PX",OW =  "OW",ZU =  "ZU",OX =  "OX",
   IK =  "IK", OR = "OR", IL = "IL",PT =  "PT",
    PY = "PY", WX = "WX",WY =  "WY",WZ =  "WZ",VC =  "VC",VD =  "VD",VE =  "VE",VY =  "VY",VX =  "VX",
    VW = "VW",VS =  "VS",TV =  "TV",KB =  "KB",
    KD = "KD",KA =  "KA", MB = "MB", PO = "PO",
    PR = "PR",PN =  "PN", OK = "OK",PL =  "PL",PS =  "PS", PM = "PM", PH = "PH",
    PV = "PV", OP = "OP",PB =  "PB",OY =  "OY",OV =  "OV",OT =  "OT",
    IA = "IA", OA = "OA",PD =  "PD",
    II = "II", IB = "IB",KK =  "KK", MM = "MM",LL =  "LL",
    HH = "HH",XZ =  "XZ",XV  =  "XV",AJ =  "AJ",AG =  "AG", OS = "OS",YG =  "YG",
    OZ = "OZ", YJ = "YJ", YF = "YF", PZ = "PZ", AF = "AF", ZQ = "ZQ",
    ZO = "ZO",

    BJ = "BJ", ZJ = "ZJ",
    XS = "XS",
    RW = "RW",
    SX = "SX",
    TZ = "TZ",
    PK = "PK",
    GO = "GO",
    RS = "RS", RD = "RD", RT = "RT", RH = "RH", RM = "RM", PE = "PE", SB = "SB", RX = "RX", RR = "RR",
    TC = "TC", PJ = "PJ", PA = "PA", ST = "ST",
    RE = "RE", SR = "SR", SA = "SA", RK = "RK", RC = "RC", RO = "RO",VH =  "VH",SH =  "SH",
    RL = "RL", RY = "RY", VO = "VO", SD = "SD", KJ = "KJ", NN = "NN", TH = "TH", PC = "PC", SC = "SC",
    VR = "VR",VN =  "VN",PW =  "PW", VL = "VL",
    RP = "RP",IU =  "IU",VT =  "VT",RI =  "RI",SK =  "SK",TR =  "TR",SP =  "SP", SM = "SM",
    SN = "SN", SZ = "SZ", PI = "PI", RB = "RB", SE = "SE", TO = "TO", SL = "SL", TL = "TL", TM = "TM",
    TI = "TI",GR =  "GR",GS =  "GS",TE =  "TE",
    TD = "TD", TW = "TW",SV =  "SV",RV =  "RV",RN =  "RN",RZ =  "RZ",SI =  "SI",RA =  "RA",
    TN = "TN", SO = "SO", GL = "GL", TK = "TK", CU = "CU", DU = "DU", EU = "EU", HU = "HU", CJ = "CJ",
    FY = "FY",BG =  "BG",GB =  "GB", FW = "FW",
    GH = "GH", FR = "FR", GK = "GK", FV = "FV", FB = "FB", GY = "GY",
    GM = "GM",FO =  "FO",
    FG = "FG", GN = "GN", GC = "GC", GW = "GW", GD = "GD", FX = "FX", CF = "CF",
    FN = "FN",FA =  "FA",FF =  "FF",FT =  "FT",GG =  "GG",GA =  "GA",
    GX = "GX",FH =  "FH",FP =  "FP",GZ =  "GZ",
    FE = "FE",FI =  "FI", FZ = "FZ", GT = "GT",
    FM = "FM", GV = "GV",FS =  "FS", CG = "CG", FD = "FD", BF = "BF",
    FC = "FC", GI = "GI", TP = "TP",SS =  "SS",SW =  "SW",TY =  "TY",TS =  "TS",
    TA = "TA",TB =  "TB",TX =  "TX",OO =  "OO", AQ = "AQ",SY =  "SY",VZ =  "VZ",VV =  "VV",
    TT = "TT",UB =  "UB", PP = "PP",
    AU = "AU", WJ = "WJ",WF =  "WF",JF =  "JF",JD =  "JD",JI =  "JI",JH =  "JH", JA = "JA",JB =  "JB",JM =  "JM",
    JJ = "JJ", LG = "LG", LQ = "LQ",
    LO = "LO",

    JE = "JE", IF = "IF", JG = "JG", JK = "JK", OJ = "OJ",
    OG = "OG", MF = "MF", MJ = "MJ", DG = "DG", CQ = "CQ", EJ = "EJ", KG = "KG", GF = "GF", GE = "GE", JC = "JC",
    IG = "IG", JL = "JL", MG = "MG",
    SF = "SF",DF =  "DF",EG =  "EG",LF =  "LF",EF =  "EF",KF =  "KF",LJ =  "LJ",BU =  "BU",
    XG = "XG",BQ =  "BQ", DQ = "DQ", DJ = "DJ",EQ =  "EQ",FQ =  "FQ",FU =  "FU",
    FK = "FK",FL =  "FL",FJ =  "FJ"
}